package sk.mrtn.pixi.client.spine;

import jsinterop.annotations.JsConstructor;
import jsinterop.annotations.JsProperty;
import jsinterop.annotations.JsType;

/**
 * Bone has a reference to a BoneData and stores the hierarchy of bones and their SRT for the current pose.
 * <p>
 * More about transformation on
 * http://www.tutorialspoint.com/computer_graphics/2d_transformation.htm
 *
 * @author Tomas Ecker
 */
@JsType(isNative = true, namespace = "PIXI.spine.core")
public class Bone {

    /**
     * The world position of the bone. Readonly.
     * @return
     */
    @JsProperty
    public double worldX;

    /**
     * The world position of the bone. Readonly.
     * @return
     */
    @JsProperty
    public double worldY;

    @JsConstructor
    public Bone(BoneData data, Skeleton skeleton, Bone parent){};

    //region AUTOGENERATED METHODS AND FIELDS - not used
    // PUBLIC STATIC FIELDS
    @JsProperty
    public static boolean yDown;
    //endregion

}
